// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App represents the main application service
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetConfigPath returns the path to the config file
 * @returns {$CancellablePromise<string>}
 */
export function GetConfigPath() {
    return $Call.ByID(4029735838);
}

/**
 * GetDefaultConfig returns the default configuration
 * @returns {$CancellablePromise<$models.AppConfig | null>}
 */
export function GetDefaultConfig() {
    return $Call.ByID(3182091318).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetSetting gets a specific setting value
 * @param {string} key
 * @returns {$CancellablePromise<any>}
 */
export function GetSetting(key) {
    return $Call.ByID(48053349, key);
}

/**
 * LoadConfig loads the application configuration
 * @returns {$CancellablePromise<$models.AppConfig | null>}
 */
export function LoadConfig() {
    return $Call.ByID(2822453907).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * SaveConfig saves the application configuration
 * @param {$models.AppConfig | null} config
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig(config) {
    return $Call.ByID(3442292638, config);
}

/**
 * SetSetting sets a specific setting value
 * @param {string} key
 * @param {any} value
 * @returns {$CancellablePromise<void>}
 */
export function SetSetting(key, value) {
    return $Call.ByID(4214292049, key, value);
}

// Private type creation functions
const $$createType0 = $models.AppConfig.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
