// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function GetMonitors() {
    return $Call.ByID(715713638).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} monitorName
 * @param {number} alpha
 * @returns {$CancellablePromise<void>}
 */
export function SetBrightness(monitorName, alpha) {
    return $Call.ByID(1985835302, monitorName, alpha);
}

/**
 * @param {string} monitorName
 * @param {number} red
 * @param {number} green
 * @param {number} blue
 * @returns {$CancellablePromise<void>}
 */
export function SetColor(monitorName, red, green, blue) {
    return $Call.ByID(797899220, monitorName, red, green, blue);
}

/**
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetEnabled(enabled) {
    return $Call.ByID(2417225210, enabled);
}

/**
 * @param {string} monitorName
 * @param {number} width
 * @returns {$CancellablePromise<void>}
 */
export function SetWidth(monitorName, width) {
    return $Call.ByID(3931514619, monitorName, width);
}

/**
 * @param {string} name
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function ToggleMonitor(name, enabled) {
    return $Call.ByID(384246375, name, enabled);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
